### PR TITLE
Track best model

### PR DESCRIPTION
**Pull request by FelixAbrahamsson**
Not sure if `BestModelTracker` is the best name for the handler triggering the `NEW_BEST_MODEL` event, open to suggestions!

### CODE REVIEW

**Comment by FelixAbrahamsson** [comment]
Tested on a dummy example btw

**Comment by FelixAbrahamsson** [comment]
Also not sure if `BestModelTracker` should be written in the more pythonic way
```python
class BestModelTracker:
    def __init__(self, model_score_function):
        self.best_score = -np.inf
        self.model_score_function = model_score_function

    def check_if_new_best_model(self, engine):
        score = self.model_score_function(engine)
        if score > self.best_score:
            self.best_score = score
            engine.fire_event(CustomEvents.NEW_BEST_MODEL)

    def attach(self, engine):
        engine.add_event_handler(
            Events.EPOCH_COMPLETED,
            lambda engine: self.check_if_new_best_model(engine)
        )
```

**Review by samedii — COMMENTED** [review]
Discussed on slack

**Review by samedii — APPROVED** [review]

**Review by Jim-Holmstroem — APPROVED** [review]

**Comment by Jim-Holmstroem** [comment]
Not sure about the naming scheme that ignite uses, usually it's best to call it something on the same line, but I'm guessing they don't have that many customtriggers implemented :P
`BestModelTrigger` could be an alternative, but I'm not sure myself

**Comment by samedii** [comment]
Agree that BestModelTrigger is a little better

**Review by samedii — APPROVED** [review]

**Pull request merged**
