### PR TITLE
Zip datasets

### PR DESCRIPTION
**Pull request by samedii**
`Dataset.zip` zips together two datasets by index creating a single pair per index.

Zip is less obvious on dataset than datastream. Maybe this should be moved over. Let's discuss

### CODE REVIEW

**Comment by samedii** [comment]
@Jim-Holmstroem Docker image seems to have failed on installing pandas somehow. Not sure how that is even possible

**Comment by Jim-Holmstroem** [comment]
looks like a network error on the CI machine, not that uncommon
i forced a rebuild and we'll see if it passes

**Comment by Jim-Holmstroem** [comment]
:tada: if only I got a dollar every time a CI server failed due to network issues

**Comment by samedii** [comment]
The new repo `aiwizo/ampli-problem` needs this. Will need to merge datasets/datastreams soon. Merging this to `datastreams` branch.

**Comment by Jim-Holmstroem** [comment]
we'll have a look at it on Monday?

**Pull request merged**
