### PR TITLE
Install and verify workflow in reference Docker

### PR DESCRIPTION
**Pull request by Jim-Holmstroem**

### CODE REVIEW

**Review by samedii — APPROVED** [review]

**Comment by Jim-Holmstroem** [comment]
waiting for https://github.com/Aiwizo/coop-article-detection/pull/60

**Comment by samedii** [comment]
Ping if you want another review ;)

**Comment by Jim-Holmstroem** [comment]
yes, sorry for spamming, github doesn't work the same as locally and github downloads faster then me :P

**Review by samedii — APPROVED** [review]
Cool :D

**Pull request merged**
