### PR TITLE
Average timer works better with multiple workers

### PR DESCRIPTION
**Pull request by samedii**

### CODE REVIEW

**Review by Jim-Holmstroem — APPROVED** [review]

**Comment by Jim-Holmstroem** [comment]
isn't 0.3 default for smoothing?

**Comment by samedii** [comment]
Yes, 0.3 is default and it does not work well when multiple workers often return results at the same time

**Comment by Jim-Holmstroem** [comment]
aha, so `0.` is "average timer"? got it

**Comment by samedii** [comment]
It is not clear at all I agree.

smoothing : float, optional
Exponential moving average smoothing factor for speed estimates (ignored in GUI mode). Ranges from 0 (average speed) to 1 (current/instantaneous speed) [default: 0.3].

**Pull request merged**
