### PR TITLE
Add function to temorarily set numpy seed

### PR DESCRIPTION
**Pull request by FelixAbrahamsson**

### CODE REVIEW

**Review by samedii — APPROVED** [review]
Would have preferred without "numpy" but sure it works :D

**Review by samedii — CHANGES_REQUESTED** [review]
Sorry I missed. Please make it a decorator

**Comment by FelixAbrahamsson** [comment]
> Would have preferred without "numpy" but sure it works :D

I'm not sure about that because it's numpy specific, otherwise it should change seeds for other libraries as well (torch, random etc)?

**Comment by FelixAbrahamsson** [comment]
> Sorry I missed. Please make it a decorator

How would you do that without knowing the seed before `fn` is called?

**Review by samedii — APPROVED** [review]
Good stuff :D

**Pull request merged**
