### PR TITLE
Fix package requirement mistake

### PR DESCRIPTION
**Pull request by FelixAbrahamsson**
ignite is not the same as pytorch-ignite

### CODE REVIEW

**Comment by FelixAbrahamsson** [comment]
Also is there a reason we need to require pytorch>=1.3.1? I think it should be ok with 1.2.0 and maybe even lower?

**Comment by samedii** [comment]
No we can probably allow lower unless we want everyone doing ml to use a later version?

**Review by samedii — APPROVED** [review]
I thought ignite was added by pip freeze? Does that not work?

**Comment by FelixAbrahamsson** [comment]
> I thought ignite was added by pip freeze? Does that not work?

Both ignite and pytorch-ignite are in requirements.txt, added by pip freeze I assume. I'm talking about the requirements in setup.py :) We should probably clean up requirements.txt at some point too.

**Review by samedii — APPROVED** [review]

**Pull request merged**
