### PR TITLE
Fix bug in train_test_split with pd Series

### PR DESCRIPTION
**Pull request by FelixAbrahamsson**
Previously, the following example
```python
import pandas as pd
import numpy as np
from workflow import train_test_split


df = pd.DataFrame(dict(a=range(10)))
df.index = df.a * 2

train_test_split(
    df, 
    key='a',
    test_size=0.2, 
    stratify=np.zeros(len(df)), 
    split_file='split.json'
)
```
resulted in 
```python
IndexingError: Unalignable boolean Series provided as indexer (index of the boolean Series and of the indexed object do not match).
```
which works fine if we remove the line `df.index = df.a * 2`. Since we only want to use `stratify` as a boolean mask we can use a numpy array instead and pandas to get value_counts.

### CODE REVIEW

**Review by samedii — COMMENTED** [review]
I don't think I completely understand the issue. I am also not sure this is solving the real issue and not just solving a symptom? Can we refactor something to make this a non-issue?

We can also allow fewer alternatives as input if that helps

**Comment by FelixAbrahamsson** [comment]
The problem is that when doing boolean indexing in pandas using a pandas Series the index of the series has to align with the index of the dataframe. In `train_test_split` we are creating a pd Series to use as boolean mask, but we are initializing the index in a way that isn't necessarily the same as the dataframe (whose index can be arbitrary). An alternative solution to what I proposed is
```python
stratify = pd.Series(stratify)
stratify.index = dataframe.index.copy()
```
but I don't think that's cleaner since we only use `stratify` to do boolean masking, for which we can just use a numpy array. We also take advantage of the `value_counts` method that pd.Series has, for which we have to convert the array to a numpy series.

**Comment by FelixAbrahamsson** [comment]
On second thought the if clause
```python
    if type(stratify) is str:
        stratify = dataframe[stratify]
```
means that we'd be running pd.Series on a pd.Series object which isn't very clean, so perhaps
```python
stratify = pd.Series(stratify)
stratify.index = dataframe.index.copy()
```
is a better solution after all.

**Comment by samedii** [comment]
I think we should move this to datastream instead and try to fix it there. Maybe we can skip stratification completely if it set to None instead

**Comment by FelixAbrahamsson** [comment]
Another option is to refactor and make stratify an optional argument, and let it be either a string (column name of dataframe) or None. This is reasonable at the moment since the function only accepts pd dataframes anyway (would also solve the ugly workarounds in ampli).

**Comment by FelixAbrahamsson** [comment]
Sounds like that's the plan then :stuck_out_tongue:

**Comment by FelixAbrahamsson** [comment]
Closing in favor of new updates to pytorch-datastream

**Pull request closed without merging**
