### PR TITLE
Synchronize publish script with readme

### PR DESCRIPTION
**Pull request by samedii**
Wanted to bump version and discovered this

### CODE REVIEW

**Comment by Jim-Holmstroem** [comment]
sorry the README should read `without-the-v` sorry for the slip

**Comment by Jim-Holmstroem** [comment]
I think the `twine` will misbehave with this

**Comment by samedii** [comment]
This is exactly what I did with twine before. It should work in that regard

**Comment by samedii** [comment]
Actually you are correct. Closing this

**Pull request closed without merging**
