### PR TITLE
Dataframe subset

### PR DESCRIPTION
**Pull request by samedii**
Specialized subset for dataframe. We could make a inheriting class instead if we prefer that pattern. Will probably add a split method (only for dataframes) later

### CODE REVIEW

**Comment by FelixAbrahamsson** [comment]
Why do you think this is necessary? To me the other method looks just as good for dataframes, if not better since `.iloc` [may sometimes return a copy](https://stackoverflow.com/questions/47972633/in-pandas-does-iloc-method-give-a-copy-or-view) of the dataframe which would cause unnecessary duplication.

**Comment by samedii** [comment]
At the moment we are using subset for 2 things:
1. Splitting (which we do in problem and in data)
2. Creating a stratified datastream

In case 1. it becomes very ugly when splitting the second time in `data` because the source is now a dataset so the code would be:
`dataset.source.source` to access the 'lightweight' metadata about each example so we can split into train/validate or gradient/early_stopping

I am more so leaning towards only having subset available when the source is a dataframe because both the current use cases are only when we have dataframes

The `coop-articles` branch does not work without this change at the moment.

Do you see a better solution? We could inherit and have a DataframeDataset that implements new methods or overrides existing. I am not sure what I think abou that though @Jim-Holmstroem 

Edit: Also I do not think a subset copy of the dataframe is something we should consider a problem we need to think about

**Comment by FelixAbrahamsson** [comment]
I see what you mean. Isn't it even worse though -  at the moment the source of a Dataset subset seems to be just a list of indices, so the actual source is inaccessible?
I don't know what the best solution is. Maybe we should do what you proposed earlier, constrain the source to only be a dataframe.

**Comment by samedii** [comment]
Ah you are right, I forgot. I could not solve it easily without passing an extra dataframe on the side.

We cannot constrain the source to only be a dataframe for all datasets if we want to support stuff like `zip`

I think the alternatives are:
- invisible `DataframeDataset`
- assertions in functions that only work with source type dataframe
- invisible `ZipDataset`

I'm leaning towards the second alternative but it would be nice to hear your and @Jim-Holmstroem 's opionion on this

Edit: I added a third alternative. It may actually be better to treat the strange alternatives like `zip` separately and let 'dataframedataset' be the default

**Comment by FelixAbrahamsson** [comment]
I think I also like the second alternative more. Also, subset would be easily implemented for any numpy array-like structure, which should cover almost any dataset I can think of.

**Review by FelixAbrahamsson — APPROVED** [review]
Approving for now so it works with article-detection, we can change things later. Seems like we might wanna revisit some things anyway.

**Comment by Jim-Holmstroem** [comment]
sorry for being slow on this, got lost in a swamped mail inbox x)
yea lets discuss it later

I agree with that numpy array-like as source would work
I need to think a few rounds on this (but not now)

**Pull request merged**
