### PR TITLE
Dynamic float format for metrics logging

### PR DESCRIPTION
**Pull request by FelixAbrahamsson**
Some metrics have an order of magnitude < -4 (e.g. MSE) which isn't readable with our current format limiter of 4 significant digits.

Example of undesired behavior:
image

Example of desired behavior:
image

### CODE REVIEW

**Comment by samedii** [comment]
Maybe it would look nicer if we always have the same number of characters?

Edit: I realize now that it would not look nice with the current 4 significants but we could go to 5

**Comment by FelixAbrahamsson** [comment]
`e-xx` is 4 characters, so in order to have 3 significant digits for the exponential format we would need 8 digits for the normal format. I'm not sure I prefer this, what do you think?

**Comment by FelixAbrahamsson** [comment]
Also bear in mind that we can't always guarantee the same nr of characters in the output since the output can be `nan` or just not a float at all.

**Comment by FelixAbrahamsson** [comment]
I'm considering changing to `if abs(value) > 1e-4 and value != 0:` since I don't like how this looks
image
Thoughts on that? Could be confusing?

**Comment by samedii** [comment]
I think that sounds fine

**Review by samedii — APPROVED** [review]
You can add your idea with 0 if you want

**Pull request merged**
