### PR TITLE
Simplify trainer validator

### PR DESCRIPTION
**Pull request by samedii**

### CODE REVIEW

**Comment by samedii** [comment]
Tested on utter

**Comment by FelixAbrahamsson** [comment]
I might be mistaken, but isn't the if-statement at line 32 in `create_standard_trainer_evaluators` covering the same thing as `create_standard_trainer_validator`? Can we remove that if-statement now?

**Review by FelixAbrahamsson — APPROVED** [review]

**Review by samedii — COMMENTED** [review]
Let's move the definition of _model_score_function to where it is used now that we do not have a common if statement anymore

**Comment by FelixAbrahamsson** [comment]
> Let's move the definition of _model_score_function to where it is used now that we do not have a common if statement anymore

Done!

**Pull request merged**
